# Generated by Django 5.0 on 2023-12-15 09:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("Title", models.CharField(max_length=40)),
                ("Description", models.TextField(max_length=300)),
                ("Previous_price", models.IntegerField(max_length=5)),
                ("Current_price", models.IntegerField(max_length=5)),
            ],
        ),
    ]
