# Generated by Django 5.0 on 2023-12-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_rename_items_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="Image_URL",
            field=models.URLField(default="https://circuitbunny.shop"),
        ),
    ]
