# Generated by Django 5.0 on 2023-12-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_alter_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="Category",
            field=models.CharField(default="Microcontrollers", max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="Current_price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="Previous_price",
            field=models.IntegerField(),
        ),
    ]
