# Generated by Django 5.0 on 2023-12-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_item_category_alter_item_current_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="Image_URL",
            field=models.URLField(default="#"),
        ),
    ]
