# Generated by Django 5.0 on 2023-12-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_alter_item_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="Description",
            field=models.TextField(),
        ),
    ]
