# Generated by Django 5.0 on 2023-12-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_alter_item_category_alter_item_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Image_URL", models.URLField(default="")),
                ("Title", models.CharField(max_length=40)),
                ("Description", models.TextField()),
            ],
        ),
    ]
