# Generated by Django 5.0 on 2023-12-15 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_rename_slider_announcements_cartitem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Announcements",
            new_name="Announcement",
        ),
    ]
