# Generated by Django 5.0 on 2023-12-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_rename_announcements_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=250)),
                ("Full_name", models.CharField(max_length=250)),
                ("Address", models.CharField(max_length=250)),
                ("Email", models.EmailField(max_length=254)),
                ("Phone_numer", models.CharField(max_length=15)),
                ("Payment_method", models.CharField(default="COD", max_length=10)),
            ],
        ),
    ]
