# Generated by Django 5.0 on 2023-12-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_preorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preorder",
            name="Payment_method",
        ),
        migrations.AddField(
            model_name="preorder",
            name="Is_COD",
            field=models.BooleanField(default=True),
        ),
    ]
