# Generated by Django 5.0 on 2023-12-16 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_remove_preorder_payment_method_preorder_is_cod"),
    ]

    operations = [
        migrations.RenameField(
            model_name="preorder",
            old_name="Phone_numer",
            new_name="Phone_number",
        ),
    ]
