# Generated by Django 5.0 on 2023-12-16 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_rename_phone_numer_preorder_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preorder",
            name="Is_COD",
        ),
    ]
