# Generated by Django 5.0 on 2023-12-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0015_remove_preorder_is_cod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="Image_URL",
            field=models.URLField(default="", max_length=1000),
        ),
    ]
