# Generated by Django 5.0 on 2023-12-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0016_alter_announcement_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="Image_URL",
            field=models.ImageField(upload_to="images"),
        ),
    ]
