# Generated by Django 5.0 on 2023-12-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0020_alter_preorder_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preorder",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
