# Generated by Django 5.0 on 2023-12-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0021_alter_preorder_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preorder",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
