# Generated by Django 5.0 on 2024-01-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0022_alter_preorder_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("items", models.CharField(max_length=5000)),
                ("Name", models.CharField(max_length=250)),
                ("Full_name", models.CharField(max_length=250)),
                ("Address", models.CharField(max_length=250)),
                ("Email", models.EmailField(max_length=254)),
                ("Phone_number", models.CharField(max_length=15)),
            ],
        ),
    ]
