# Generated by Django 5.0 on 2024-01-06 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0023_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="Name",
        ),
    ]
