# Generated by Django 5.0 on 2024-01-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0024_remove_order_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderUpdate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Order_ID", models.IntegerField(default="")),
                ("Description", models.CharField(max_length=5000)),
                ("Estimated_delivery", models.CharField(default="", max_length=50)),
            ],
        ),
    ]
