# Generated by Django 5.0 on 2024-01-07 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0025_orderupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderupdate",
            name="Timestamp",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderupdate",
            name="Estimated_delivery",
            field=models.CharField(max_length=50),
        ),
    ]
