# Generated by Django 5.0 on 2024-01-07 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0026_orderupdate_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderupdate",
            name="Estimated_delivery",
        ),
    ]
