# Generated by Django 5.0 on 2024-01-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0027_remove_orderupdate_estimated_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="TotalPrice",
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
